### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'get'

### ISSUE THREAD

**Issue by LorenzoBonasera** [anyoptimization/pymoo#353]
Hi everyone,

I updated Pymoo from version 0.5.0 to version 0.6.0 and I ran the same code solving an ElementWiseProblem via BRKGA.
I get the following error: "AttributeError: 'numpy.int64' object has no attribute 'get'".

It seems that NumPy data objects are no longer supported, but I cannot find a solution in the documentation.
I kindly ask for you help

**Comment by blankjul** [comment]
Can you provide some code to reproduce the problem? 

I was just checking the example on the homepage and that seems to work. In general, Numpy has switched to the Python data types, such as `int`, `float`, and so on. 

https://numpy.org/devdocs/release/1.20.0-notes.html

**Comment by blankjul** [comment]
Thank you for providing the solution. I have just committed the changes. 
Please let me know if this works now.

**Comment by wolfgangdu** [comment]
Thank you!
Tested and working.

**Comment by LorenzoBonasera** [comment]
It still does not work. This error comes from the line:

  File "C:....\pymoo\core\crossover.py", line 31, in <listcomp>
    X = np.swapaxes(np.array([[parent.get("X") for parent in mating] for mating in pop]), 0, 1)
AttributeError: 'numpy.int64' object has no attribute 'get'

**Comment by wolfgangdu** [comment]
Could you provide a minimal working example to reproduce your error?

**Comment by blankjul** [comment]
@LorenzoBonasera Yes please provide a minimal working example to us so that we can see where what goes wrong.

**Comment by bruscalia** [comment]
Hi @LorenzoBonasera. We are working on your example. I had some problems with BRKGA too, although they do not occur with Julian. Probably it has something to do with OS. It is likely that this problem is related to parent selection and the "elite" attribute.

Can you try to instantiate the parent selection class as the following?

`class EliteBiasedSelection(Selection):
    
    def __init__(self, elite_size, **kwargs) -> None:
        super().__init__(**kwargs)
        self.elite_size = elite_size

    def _do(self, problem, pop, n_select, n_parents, **kwargs):

        # do the mating selection - always one elite and one non-elites
        s_elite = np.random.choice(np.arange(self.elite_size), size=n_select, replace=True)
        s_non_elite = np.random.choice(np.arange(len(pop) - self.elite_size) + self.elite_size, size=n_select)

        return np.column_stack([s_elite, s_non_elite])`

You would also need to change the super().__init__ within BRKGA in the selection keyword argument.

`selection=EliteBiasedSelection(n_elites)`

Let me know if it works for you!

We will probably do some updates in BRKGA for the next release too.

**Comment by LorenzoBonasera** [comment]
Hi @bruscalia, now it works. I'm using Windows 11 as OS.

Thank you very much!
